// generated by analyze_beats.py from cuts/*.json; loaded by covered-film.html
window.COVERED_CUTS = {
 "flames": {
  "name": "flames",
  "title": "\"Dancing in the Flames\", The Weeknd",
  "placeholder": true,
  "audio_source": "out/click/flames-click.wav",
  "bpm": 120.001,
  "offset_s": 16.0004,
  "beats_per_bar": 4,
  "unit": 1.0,
  "stretch_bars": [],
  "beat_times": [
   0.0,
   0.4996,
   0.9992,
   1.4992,
   1.9984,
   2.4977,
   2.9969,
   3.4969,
   3.9969,
   4.4989,
   4.9989,
   5.4989,
   5.9981,
   6.4973,
   6.9973,
   7.4973,
   7.9993,
   8.4993,
   8.9993,
   9.4985,
   9.9977,
   10.4977,
   10.9977,
   11.4997,
   11.9997,
   12.4997,
   12.9989,
   13.4981,
   13.9974,
   14.4974,
   14.9973,
   15.4993,
   15.9993,
   16.4993,
   16.9985,
   17.4978,
   17.9978,
   18.4978,
   18.9997,
   19.4997,
   19.9997,
   20.4989,
   20.9982,
   21.4974,
   21.9974,
   22.4974,
   22.9994,
   23.4994,
   23.9994,
   24.4986,
   24.9978,
   25.4978,
   25.9978,
   26.4998,
   26.9998,
   27.4998,
   27.999,
   28.4982,
   28.9974,
   29.4974,
   29.9974,
   30.4994,
   30.9994,
   31.4994,
   31.9986,
   32.4979,
   32.9979,
   33.4978,
   33.9998,
   34.4998,
   34.9998,
   35.4994,
   35.999
  ],
  "loop": false,
  "punch": false,
  "outro": {
   "end_bar": 17,
   "tail_s": 0.6
  },
  "section": {
   "start_s": 16.0004,
   "end_s": 48.0,
   "bars": 16
  },
  "candidates": [
   {
    "bar": 8,
    "start": 16.0,
    "end": 48.0,
    "score": 1.899,
    "energy": 1.0,
    "build": 0.999,
    "mid_phrase": false
   },
   {
    "bar": 32,
    "start": 64.0,
    "end": 95.999,
    "score": 1.574,
    "energy": 1.0,
    "build": 0.458,
    "mid_phrase": false
   },
   {
    "bar": 9,
    "start": 18.0,
    "end": 50.0,
    "score": 1.528,
    "energy": 0.971,
    "build": 0.75,
    "mid_phrase": true
   },
   {
    "bar": 10,
    "start": 20.0,
    "end": 52.0,
    "score": 1.329,
    "energy": 0.943,
    "build": 0.5,
    "mid_phrase": true
   },
   {
    "bar": 31,
    "start": 62.0,
    "end": 94.0,
    "score": 1.216,
    "energy": 0.971,
    "build": 0.229,
    "mid_phrase": true
   },
   {
    "bar": 11,
    "start": 22.0,
    "end": 54.0,
    "score": 1.137,
    "energy": 0.914,
    "build": 0.25,
    "mid_phrase": true
   },
   {
    "bar": 7,
    "start": 14.0,
    "end": 46.0,
    "score": 1.118,
    "energy": 0.938,
    "build": 0.501,
    "mid_phrase": true
   },
   {
    "bar": 30,
    "start": 60.0,
    "end": 92.0,
    "score": 1.03,
    "energy": 0.943,
    "build": -0.0,
    "mid_phrase": true
   }
  ],
  "hits": {},
  "duration_s": 32.5986,
  "mix": "out/click/flames-mix.wav",
  "sounds": [
   {
    "story_beat": 1.0,
    "sound": "tap",
    "t": 0.4996
   },
   {
    "story_beat": 16.0,
    "sound": "tap",
    "t": 7.9993
   },
   {
    "story_beat": 21.0,
    "sound": "tap",
    "t": 10.4977
   },
   {
    "story_beat": 24.0,
    "sound": "side",
    "t": 11.9997
   },
   {
    "story_beat": 25.0,
    "sound": "side",
    "t": 12.4997
   },
   {
    "story_beat": 27.0,
    "sound": "check",
    "t": 13.4981
   },
   {
    "story_beat": 29.0,
    "sound": "tick",
    "t": 14.4974
   },
   {
    "story_beat": 29.25,
    "sound": "tick",
    "t": 14.6224
   },
   {
    "story_beat": 29.5,
    "sound": "tick",
    "t": 14.7474
   },
   {
    "story_beat": 30.0,
    "sound": "tap",
    "t": 14.9973
   },
   {
    "story_beat": 37.0,
    "sound": "ping",
    "t": 18.4978
   },
   {
    "story_beat": 38.0,
    "sound": "tick",
    "t": 18.9997
   },
   {
    "story_beat": 38.25,
    "sound": "tick",
    "t": 19.1247
   },
   {
    "story_beat": 38.5,
    "sound": "tick",
    "t": 19.2497
   },
   {
    "story_beat": 38.75,
    "sound": "tick",
    "t": 19.3747
   },
   {
    "story_beat": 41.0,
    "sound": "tick",
    "t": 20.4989
   },
   {
    "story_beat": 43.0,
    "sound": "tick",
    "t": 21.4974
   },
   {
    "story_beat": 43.25,
    "sound": "tick",
    "t": 21.6224
   },
   {
    "story_beat": 45.0,
    "sound": "tick",
    "t": 22.4974
   },
   {
    "story_beat": 45.25,
    "sound": "tick",
    "t": 22.6229
   },
   {
    "story_beat": 45.5,
    "sound": "tick",
    "t": 22.7484
   }
  ]
 },
 "mixkit": {
  "name": "mixkit",
  "title": "\"House Vibes\", Alejandro Maga\u00f1a (A. M.), Mixkit #129",
  "placeholder": false,
  "audio_source": "assets/source/mixkit-house-vibes-129.mp3",
  "bpm": 119.998,
  "grid_bpm": 120,
  "note": "measured 119.998 BPM; analyze_beats.py build time-stretches the loop by 120/119.998 so 48 beats are exactly 24.000 s",
  "offset_s": 16.0842,
  "beats_per_bar": 4,
  "unit": 1,
  "stretch_bars": [],
  "beat_times": null,
  "loop": true,
  "punch": false,
  "outro": null,
  "section": {
   "start_s": 16.0842,
   "end_s": 40.0846,
   "bars": 12
  },
  "hits": {},
  "duration_s": 24.0,
  "mix": "assets/mix.wav"
 },
 "power": {
  "name": "power",
  "title": "\"POWER\", Kanye West",
  "placeholder": true,
  "audio_source": "out/click/power-click.wav",
  "bpm": 77.0,
  "offset_s": 24.935,
  "beats_per_bar": 4,
  "unit": 0.5,
  "stretch_bars": [
   3,
   5,
   7,
   11
  ],
  "beat_times": [
   0.0,
   0.7785,
   1.5584,
   2.3377,
   3.1159,
   3.8951,
   4.6744,
   5.4536,
   6.2328,
   7.0111,
   7.7903,
   8.5709,
   9.3501,
   10.1283,
   10.9076,
   11.6882,
   12.4674,
   13.2456,
   14.0249,
   14.8054,
   15.5847,
   16.3629,
   17.1421,
   17.9214,
   18.7006,
   19.4798,
   20.2581,
   21.0373,
   21.8179,
   22.5971,
   23.3753,
   24.1546,
   24.9351,
   25.7137,
   26.4922
  ],
  "loop": true,
  "punch": true,
  "outro": null,
  "section": {
   "start_s": 24.935,
   "end_s": 49.8702,
   "bars": 8
  },
  "candidates": [
   {
    "bar": 7,
    "start": 24.935,
    "end": 49.87,
    "score": 1.9,
    "energy": 1.0,
    "build": 1.0,
    "mid_phrase": false
   },
   {
    "bar": 8,
    "start": 28.052,
    "end": 52.987,
    "score": 1.75,
    "energy": 1.0,
    "build": 0.75,
    "mid_phrase": true
   },
   {
    "bar": 9,
    "start": 31.169,
    "end": 56.104,
    "score": 1.6,
    "energy": 1.0,
    "build": 0.5,
    "mid_phrase": true
   },
   {
    "bar": 31,
    "start": 99.741,
    "end": 124.676,
    "score": 1.574,
    "energy": 1.0,
    "build": 0.458,
    "mid_phrase": false
   },
   {
    "bar": 32,
    "start": 102.857,
    "end": 127.793,
    "score": 1.506,
    "energy": 1.0,
    "build": 0.343,
    "mid_phrase": true
   },
   {
    "bar": 10,
    "start": 34.286,
    "end": 59.221,
    "score": 1.45,
    "energy": 1.0,
    "build": 0.25,
    "mid_phrase": true
   },
   {
    "bar": 33,
    "start": 105.974,
    "end": 130.91,
    "score": 1.437,
    "energy": 1.0,
    "build": 0.229,
    "mid_phrase": true
   },
   {
    "bar": 34,
    "start": 109.091,
    "end": 134.026,
    "score": 1.368,
    "energy": 1.0,
    "build": 0.114,
    "mid_phrase": true
   }
  ],
  "hits": {},
  "duration_s": 24.9351,
  "mix": "out/click/power-mix.wav",
  "sounds": [
   {
    "story_beat": 1.0,
    "sound": "tap",
    "t": 0.3892
   },
   {
    "story_beat": 16.0,
    "sound": "tap",
    "t": 7.7903
   },
   {
    "story_beat": 21.0,
    "sound": "tap",
    "t": 11.2979
   },
   {
    "story_beat": 24.0,
    "sound": "side",
    "t": 12.4674
   },
   {
    "story_beat": 25.0,
    "sound": "side",
    "t": 13.2456
   },
   {
    "story_beat": 27.0,
    "sound": "check",
    "t": 14.8054
   },
   {
    "story_beat": 29.0,
    "sound": "tick",
    "t": 15.9738
   },
   {
    "story_beat": 29.25,
    "sound": "tick",
    "t": 16.0711
   },
   {
    "story_beat": 29.5,
    "sound": "tick",
    "t": 16.1684
   },
   {
    "story_beat": 30.0,
    "sound": "tap",
    "t": 16.3629
   },
   {
    "story_beat": 37.0,
    "sound": "ping",
    "t": 19.0902
   },
   {
    "story_beat": 38.0,
    "sound": "tick",
    "t": 19.4798
   },
   {
    "story_beat": 38.25,
    "sound": "tick",
    "t": 19.5771
   },
   {
    "story_beat": 38.5,
    "sound": "tick",
    "t": 19.6744
   },
   {
    "story_beat": 38.75,
    "sound": "tick",
    "t": 19.7717
   },
   {
    "story_beat": 41.0,
    "sound": "tick",
    "t": 21.0373
   },
   {
    "story_beat": 43.0,
    "sound": "tick",
    "t": 22.5971
   },
   {
    "story_beat": 43.25,
    "sound": "tick",
    "t": 22.7917
   },
   {
    "story_beat": 45.0,
    "sound": "tick",
    "t": 23.7649
   },
   {
    "story_beat": 45.25,
    "sound": "tick",
    "t": 23.8624
   },
   {
    "story_beat": 45.5,
    "sound": "tick",
    "t": 23.9598
   }
  ]
 }
};
