// generated by analyze_beats.py from cuts/*.json; loaded by covered-film.html
window.COVERED_CUTS = {
 "flames": {
  "name": "flames",
  "title": "\"Dancing in the Flames\", The Weeknd",
  "placeholder": false,
  "audio_source": "assets/music/dancing-in-the-flames.mp3",
  "bpm": 156.002,
  "offset_s": 28.6973,
  "beats_per_bar": 4,
  "unit": 1.0,
  "stretch_bars": [],
  "beat_times": [
   0.0,
   0.3846,
   0.7692,
   1.1538,
   1.5384,
   1.9231,
   2.3077,
   2.6923,
   3.0769,
   3.4601,
   3.8461,
   4.2307,
   4.6153,
   4.9969,
   5.3846,
   5.7661,
   6.1507,
   6.5384,
   6.923,
   7.3076,
   7.6922,
   8.0768,
   8.4614,
   8.8461,
   9.2307,
   9.6153,
   9.9999,
   10.3845,
   10.7691,
   11.1537,
   11.5383,
   11.923,
   12.3076,
   12.6922,
   13.0768,
   13.4614,
   13.846,
   14.2306,
   14.6152,
   14.9998,
   15.3845,
   15.7691,
   16.1537,
   16.5383,
   16.9229,
   17.3075,
   17.6921,
   18.0767,
   18.4613,
   18.846,
   19.2306,
   19.6152,
   19.9998,
   20.3844,
   20.769,
   21.1536,
   21.5382,
   21.9228,
   22.3075,
   22.6921,
   23.0767,
   23.4613,
   23.8459,
   24.2305,
   24.6151,
   24.9997,
   25.3843,
   25.769,
   26.1536,
   26.5382,
   26.9195,
   27.3026,
   27.6858
  ],
  "loop": false,
  "punch": false,
  "outro": {
   "end_bar": 17,
   "tail_s": 0.6
  },
  "section": {
   "start_s": 28.6973,
   "end_s": 53.3125,
   "bars": 16
  },
  "candidates": [
   {
    "bar": 18,
    "start": 28.697,
    "end": 53.312,
    "score": 1.408,
    "energy": 0.905,
    "build": 0.437,
    "mid_phrase": false
   },
   {
    "bar": 93,
    "start": 144.065,
    "end": 168.68,
    "score": 1.356,
    "energy": 0.914,
    "build": 0.337,
    "mid_phrase": true
   },
   {
    "bar": 19,
    "start": 30.22,
    "end": 54.835,
    "score": 1.354,
    "energy": 0.904,
    "build": 0.353,
    "mid_phrase": true
   },
   {
    "bar": 94,
    "start": 145.603,
    "end": 170.218,
    "score": 1.339,
    "energy": 0.918,
    "build": 0.3,
    "mid_phrase": false
   },
   {
    "bar": 95,
    "start": 147.141,
    "end": 171.757,
    "score": 1.282,
    "energy": 0.922,
    "build": 0.201,
    "mid_phrase": true
   },
   {
    "bar": 20,
    "start": 31.758,
    "end": 56.373,
    "score": 1.271,
    "energy": 0.904,
    "build": 0.214,
    "mid_phrase": true
   },
   {
    "bar": 58,
    "start": 90.219,
    "end": 114.834,
    "score": 1.243,
    "energy": 0.902,
    "build": 0.166,
    "mid_phrase": false
   },
   {
    "bar": 57,
    "start": 88.68,
    "end": 113.296,
    "score": 1.24,
    "energy": 0.902,
    "build": 0.161,
    "mid_phrase": true
   }
  ],
  "hits": {
   "case": {
    "story_beat": 8.0,
    "t": 3.0665,
    "onset": 0.13
   },
   "check": {
    "story_beat": 27.0,
    "t": 10.3692,
    "onset": 0.184
   },
   "sum": {
    "story_beat": 41.0,
    "t": 15.7562,
    "onset": 0.099
   },
   "mark": {
    "story_beat": 56.0,
    "t": 21.5264,
    "onset": 0.074
   }
  },
  "duration_s": 25.2151,
  "mix": "assets/music/derived/flames-mix.wav",
  "sounds": [
   {
    "story_beat": 1.0,
    "sound": "tap",
    "t": 0.3846
   },
   {
    "story_beat": 16.0,
    "sound": "tap",
    "t": 6.1507
   },
   {
    "story_beat": 21.0,
    "sound": "tap",
    "t": 8.0768
   },
   {
    "story_beat": 24.0,
    "sound": "side",
    "t": 9.2307
   },
   {
    "story_beat": 25.0,
    "sound": "side",
    "t": 9.6153
   },
   {
    "story_beat": 27.0,
    "sound": "check",
    "t": 10.3692
   },
   {
    "story_beat": 29.0,
    "sound": "tick",
    "t": 11.1537
   },
   {
    "story_beat": 29.25,
    "sound": "tick",
    "t": 11.2499
   },
   {
    "story_beat": 29.5,
    "sound": "tick",
    "t": 11.346
   },
   {
    "story_beat": 30.0,
    "sound": "tap",
    "t": 11.5383
   },
   {
    "story_beat": 37.0,
    "sound": "ping",
    "t": 14.2306
   },
   {
    "story_beat": 38.0,
    "sound": "tick",
    "t": 14.6152
   },
   {
    "story_beat": 38.25,
    "sound": "tick",
    "t": 14.7113
   },
   {
    "story_beat": 38.5,
    "sound": "tick",
    "t": 14.8075
   },
   {
    "story_beat": 38.75,
    "sound": "tick",
    "t": 14.9037
   },
   {
    "story_beat": 41.0,
    "sound": "tick",
    "t": 15.7562
   },
   {
    "story_beat": 43.0,
    "sound": "tick",
    "t": 16.5383
   },
   {
    "story_beat": 43.25,
    "sound": "tick",
    "t": 16.6345
   },
   {
    "story_beat": 45.0,
    "sound": "tick",
    "t": 17.3075
   },
   {
    "story_beat": 45.25,
    "sound": "tick",
    "t": 17.4036
   },
   {
    "story_beat": 45.5,
    "sound": "tick",
    "t": 17.4998
   }
  ]
 },
 "mixkit": {
  "name": "mixkit",
  "title": "\"House Vibes\", Alejandro Maga\u00f1a (A. M.), Mixkit #129",
  "placeholder": false,
  "audio_source": "assets/source/mixkit-house-vibes-129.mp3",
  "bpm": 119.998,
  "grid_bpm": 120,
  "note": "measured 119.998 BPM; analyze_beats.py build time-stretches the loop by 120/119.998 so 48 beats are exactly 24.000 s",
  "offset_s": 16.0842,
  "beats_per_bar": 4,
  "unit": 1,
  "stretch_bars": [],
  "beat_times": null,
  "loop": true,
  "punch": false,
  "outro": null,
  "section": {
   "start_s": 16.0842,
   "end_s": 40.0846,
   "bars": 12
  },
  "hits": {},
  "duration_s": 24.0,
  "mix": "assets/mix.wav"
 },
 "power": {
  "name": "power",
  "title": "\"POWER\", Kanye West",
  "placeholder": false,
  "audio_source": "assets/music/power.mp3",
  "bpm": 77.0,
  "offset_s": 224.5933,
  "beats_per_bar": 4,
  "unit": 0.5,
  "stretch_bars": [
   3,
   5,
   7,
   11
  ],
  "beat_times": [
   0.0,
   0.779145,
   1.55829,
   2.337534,
   3.116679,
   3.895824,
   4.674969,
   5.454214,
   6.233358,
   7.012503,
   7.791648,
   8.570893,
   9.350037,
   10.129182,
   10.908327,
   11.687472,
   12.466717,
   13.245861,
   14.025006,
   14.804151,
   15.583396,
   16.362541,
   17.141685,
   17.92083,
   18.700075,
   19.47922,
   20.258365,
   21.037509,
   21.816654,
   22.595899,
   23.375044,
   24.154189,
   24.933333,
   25.712578,
   26.491723
  ],
  "loop": true,
  "punch": true,
  "outro": null,
  "section": {
   "start_s": 224.5933,
   "end_s": 249.5285,
   "bars": 8
  },
  "candidates": [
   {
    "bar": 72,
    "start": 224.593,
    "end": 249.528,
    "score": 1.428,
    "energy": 0.924,
    "build": 0.389,
    "mid_phrase": false
   },
   {
    "bar": 15,
    "start": 46.912,
    "end": 71.847,
    "score": 1.329,
    "energy": 0.963,
    "build": 0.159,
    "mid_phrase": true
   },
   {
    "bar": 14,
    "start": 43.795,
    "end": 68.73,
    "score": 1.328,
    "energy": 0.963,
    "build": 0.157,
    "mid_phrase": true
   },
   {
    "bar": 13,
    "start": 40.678,
    "end": 65.613,
    "score": 1.327,
    "energy": 0.964,
    "build": 0.155,
    "mid_phrase": true
   },
   {
    "bar": 31,
    "start": 96.782,
    "end": 121.717,
    "score": 1.32,
    "energy": 0.962,
    "build": 0.128,
    "mid_phrase": true
   },
   {
    "bar": 12,
    "start": 37.561,
    "end": 62.496,
    "score": 1.314,
    "energy": 0.961,
    "build": 0.14,
    "mid_phrase": false
   },
   {
    "bar": 29,
    "start": 90.548,
    "end": 115.484,
    "score": 1.308,
    "energy": 0.958,
    "build": 0.126,
    "mid_phrase": true
   },
   {
    "bar": 30,
    "start": 93.665,
    "end": 118.6,
    "score": 1.3,
    "energy": 0.959,
    "build": 0.111,
    "mid_phrase": true
   }
  ],
  "hits": {
   "flip": {
    "story_beat": 17.25,
    "t": 8.695384,
    "onset": 0.116
   },
   "sum": {
    "story_beat": 41.0,
    "t": 21.017011,
    "onset": 0.087
   }
  },
  "time_stretch": 0.99992915,
  "duration_s": 24.9333,
  "mix": "assets/music/derived/power-mix.wav",
  "sounds": [
   {
    "story_beat": 1.0,
    "sound": "tap",
    "t": 0.3896
   },
   {
    "story_beat": 16.0,
    "sound": "tap",
    "t": 7.7916
   },
   {
    "story_beat": 21.0,
    "sound": "tap",
    "t": 11.2979
   },
   {
    "story_beat": 24.0,
    "sound": "side",
    "t": 12.4667
   },
   {
    "story_beat": 25.0,
    "sound": "side",
    "t": 13.2459
   },
   {
    "story_beat": 27.0,
    "sound": "check",
    "t": 14.8042
   },
   {
    "story_beat": 29.0,
    "sound": "tick",
    "t": 15.973
   },
   {
    "story_beat": 29.25,
    "sound": "tick",
    "t": 16.0704
   },
   {
    "story_beat": 29.5,
    "sound": "tick",
    "t": 16.1678
   },
   {
    "story_beat": 30.0,
    "sound": "tap",
    "t": 16.3625
   },
   {
    "story_beat": 37.0,
    "sound": "ping",
    "t": 19.0896
   },
   {
    "story_beat": 38.0,
    "sound": "tick",
    "t": 19.4792
   },
   {
    "story_beat": 38.25,
    "sound": "tick",
    "t": 19.5766
   },
   {
    "story_beat": 38.5,
    "sound": "tick",
    "t": 19.674
   },
   {
    "story_beat": 38.75,
    "sound": "tick",
    "t": 19.7714
   },
   {
    "story_beat": 41.0,
    "sound": "tick",
    "t": 21.017
   },
   {
    "story_beat": 43.0,
    "sound": "tick",
    "t": 22.5959
   },
   {
    "story_beat": 43.25,
    "sound": "tick",
    "t": 22.7907
   },
   {
    "story_beat": 45.0,
    "sound": "tick",
    "t": 23.7646
   },
   {
    "story_beat": 45.25,
    "sound": "tick",
    "t": 23.862
   },
   {
    "story_beat": 45.5,
    "sound": "tick",
    "t": 23.9594
   }
  ]
 }
};
